#!/bin/bash
#
# chkconfig: - 64 36
#This script used to stop and start zabbix_agent
#
#	by wangdd 2015/10/9
#
zabbix_path="/usr/local/zabbix"
config_file="zabbix_agentd.conf"
cmd="$zabbix_path/sbin/zabbix_agentd"
pids=`ps -ef | grep zabbix_agentd | grep -v grep | awk '{print $2}'`
pid_agent=`ps -ef | grep -E "zabbix_agentd.conf" | grep -v grep | awk '{print $2}'`
##start function
function start(){
	$cmd -c $zabbix_path/etc/$config_file
	[ $? -eq 0 ] && echo "zabbix_agent start success"
}
##stop function
function stop(){
	for pid in $pids
	do 
		kill -9 $pid
	done
	[ $? -eq 0 ] && echo "zabbix_agent stop"
}
##status function
function status(){
	if [ ! -z "$pids" ];then
		echo "zabbix_agent is running"
	else 
		echo "zabbix_agent stoped"
	fi
}
#reload configure file
function reload(){
		kill -HUP $pid_agent
		[ $? -eq 0 ] && echo "zabbix_agent reload success"
		
}
case $1 in
	start)
			start
			;;
	stop)
			stop
			;;
	restart)
			stop
			start
			;;
	status)
		status
		;;
	reload)
		reload
		;;
	*)
		s=${0##*/}
		echo "Usage: service $s {start|stop|restart|reload|status}"
		exit 1
		;;
esac
