#!/bin/sh
#chkconfig:   - 85 15
#
# Zabbix daemon start/stop script.
#


NAME=zabbix_server
DAEMON=/usr/local/zabbix/sbin/${NAME}
DESC="Zabbix server daemon"
PID=/tmp/$NAME.pid

test -f $DAEMON || exit 0

case "$1" in
  start)
	echo "Starting $DESC: $NAME"
	if [ -x ${DAEMON} ];then
		echo "Start $NAME"
      		$DAEMON
    	else
    		echo "Can't find file ${DAEMON}."
      		echo "${NAME} NOT started."
    	fi
	;;
  stop)
	echo "Stopping $DESC: $NAME"
	if [ -s ${PID} ];then
      		if kill `cat ${PID}` >/dev/null 2>&1
      		then
        		echo "${NAME} stoped"
       			rm -f ${PID}
      		fi
    	fi
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
